### ISSUE TITLE
World generation tab not showing

### ISSUE THREAD

**Issue by Shroototem** [theorbtwo/RoughlyEnoughResources#29]
Minecraft Version: 1.16.5
RER Version: v2.1.3
REI Version: v5.11.218
Java Version: 1.8.0_281 64bit
Windows 10 Pro 64bit

Issue image:
![image](https://user-images.githubusercontent.com/47718633/119604856-bea6c080-bdbd-11eb-82cb-501b52f39471.png)

Expected image:
![image](https://user-images.githubusercontent.com/47718633/119605356-a6837100-bdbe-11eb-8bc5-3096f3921d1c.png)

List of all mods:
![image](https://user-images.githubusercontent.com/47718633/119605205-5c01f480-bdbe-11eb-98bd-b29465ac9f0a.png)

**Comment by theorbtwo** [comment]
Is this a superflat world?  Does iron ore actually generate in it?  If it does not, this is expected behavior.  

Try asking for recipes for plain stone -- something which does actually naturally generate.  Alternatively, try clicking on the text that says "block loot drop", which will cause REI to show all recipes in all categories, and you should be able to find the worldgen recipe categories from there -- not that they will be terribly interesting in a superflat world.

(If the point of the command blocks I see in the background of that shot is to create more interesting new blocks, note that those happen after world generation, and thus won't be included in the rer worldgen recipes.)

I am closing this report, and will reopen if you comment giving information that doesn't agree with this theory.

**Comment by Shroototem** [comment]
Oh my God... I'm very sorry. It was on a superflat world and I didn't think anything of it. Thank you for your time though.
